name: build

on: [push, pull_request]

jobs:
  build_win:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-15, macos-15-intel]

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64

      - name: Prepare circos
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          wget --no-check-certificate https://circos.ca/distribution/circos-0.69-10.tgz
          tar xzvf circos-0.69-10.tgz
          mv circos-0.69-10 circos

      - name: Prepare circos
        if: runner.os != 'Windows'
        run: |
          wget https://circos.ca/distribution/circos-0.69-10.tgz
          tar xzvf circos-0.69-10.tgz
          mv circos-0.69-10 circos

      - name: Install blobtk
        if: matrix.os == 'windows-2022'
        run: pip install https://github.com/lmdu/blobtk-wheel/releases/download/0.7.10.post1/blobtk-0.7.10.post1-cp312-cp312-win_amd64.whl

      - name: Install blobtk
        if: matrix.os == 'ubuntu-22.04'
        run: pip install https://github.com/lmdu/blobtk-wheel/releases/download/0.7.10.post1/blobtk-0.7.10.post1-cp312-cp312-manylinux_2_28_x86_64.whl
  
      - name: Install blobtk
        if: matrix.os == 'macos-15'
        run: pip install https://github.com/lmdu/blobtk-wheel/releases/download/0.7.10.post1/blobtk-0.7.10.post1-cp312-cp312-macosx_11_0_arm64.whl

      - name: Install blobtk
        if: matrix.os == 'macos-15-intel'
        run: pip install https://github.com/lmdu/blobtk-wheel/releases/download/0.7.10.post1/blobtk-0.7.10.post1-cp312-cp312-macosx_10_13_x86_64.whl
          
      - name: Install requirements
        run: pip install -r src/requirements.txt

      - name: Build executable
        run: pyinstaller package/build.spec

      - name: Package
        if: runner.os == 'Windows'
        run: |
          $line = Select-String -Path src\config.py -Pattern 'APP_VERSION =' | Out-String
          $version = $line.Split('"')[1]
          iscc /DMyAppVersion=$version package/build_win_installer.iss

      - name: Package
        if: runner.os == 'Linux'
        run: |
          version=`awk '/^APP_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          cd dist
          chmod a+x ../package/build_linux_desktop.sh
          ../package/build_linux_desktop.sh $version

      - name: Package
        if: runner.os == 'macOS'
        run: |
          version=`awk '/^APP_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          npm install --global create-dmg
          cd dist
          create-dmg Circhart.app || test -f Circhart\ 0.0.0.dmg
          mv Circhart\ 0.0.0.dmg Circhart-v${version}-macos-x64.dmg

      - uses: actions/upload-artifact@v4
        with:
          name: Circhart-x64
          path: |
            dist/*.exe
            dist/*.deb
            dist/*.tar.gz
            dist/*.AppImage
            dist/*.dmg

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.exe
            dist/*.deb
            dist/*.tar.gz
            dist/*.AppImage
            dist/*.dmg

