name: build

on: [push, pull_request]

jobs:
  build_win:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-15, macos-15-intel]

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          msystem: MINGW64

      - name: Prepare circos
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          wget --no-check-certificate --quiet https://circos.ca/distribution/circos-0.69-10.tgz
          tar xzvf circos-0.69-10.tgz
          mv circos-0.69-10 src/circos

      - name: Prepare circos
        if: runner.os != 'Windows'
        run: |
          wget --no-check-certificate --quiet https://circos.ca/distribution/circos-0.69-10.tgz
          tar xzvf circos-0.69-10.tgz
          mv circos-0.69-10 src/circos

      - name: Install blobtk
        if: matrix.os == 'windows-2022'
        run: |
          echo "BLOBTK_WHEEL=blobtk-0.7.10.post1-cp312-cp312-win_amd64.whl" >> ${GITHUB_ENV}
          wget --no-check-certificate --quiet https://github.com/lmdu/blobtk-wheel/releases/download/0.7.10.post1/${{env.BLOBTK_WHEEL}}

      - name: Install blobtk
        if: matrix.os == 'ubuntu-22.04'
        run: |
          echo "BLOBTK_WHEEL=blobtk-0.7.10.post1-cp312-cp312-manylinux_2_28_x86_64.whl" >> ${GITHUB_ENV}
          wget --no-check-certificate --quiet https://github.com/lmdu/blobtk-wheel/releases/download/0.7.10.post1/${{env.BLOBTK_WHEEL}}

      - name: Install blobtk
        if: matrix.os == 'macos-15'
        run: |
          echo "BLOBTK_WHEEL=blobtk-0.7.10.post1-cp312-cp312-macosx_11_0_arm64.whl" >> ${GITHUB_ENV}
          wget --no-check-certificate --quiet https://github.com/lmdu/blobtk-wheel/releases/download/0.7.10.post1/${{env.BLOBTK_WHEEL}}

      - name: Install blobtk
        if: matrix.os == 'macos-15-intel'
        run: |
          echo "BLOBTK_WHEEL=blobtk-0.7.10.post1-cp312-cp312-macosx_10_13_x86_64.whl" >> ${GITHUB_ENV}
          wget --no-check-certificate --quiet https://github.com/lmdu/blobtk-wheel/releases/download/0.7.10.post1/${{env.BLOBTK_WHEEL}}

      - name: Build executable
        run: |
          ls -l
          echo ${{env.BLOBTK_WHEEL}}
          python -m venv cct_venv
          source cct_venv/bin/activate
          pip install ${{env.BLOBTK_WHEEL}}
          pip install -r src/requirements.txt
          pyinstaller package/build.spec

      - name: Windows Package
        if: runner.os == 'Windows'
        run: |
          $line = Select-String -Path src\config.py -Pattern 'APP_VERSION =' | Out-String
          $version = $line.Split('"')[1]
          iscc /DMyAppVersion=$version package/build_win_installer.iss

      - name: Ubuntu Package
        if: matrix.os == 'ubuntu-22.04'
        run: |
          version=`awk '/^APP_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          chmod a+x package/build_linux_installer.sh
          package/build_linux_installer.sh $version deb

      - name: MacOS ARM Package
        if: matrix.os == 'macos-15'
        run: |
          version=`awk '/^APP_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          chmod a+x package/build_mac_installer.sh
          package/build_mac_installer.sh $version arm64

      - name: MacOS X64 Package
        if: matrix.os == 'macos-15-intel'
        run: |
          version=`awk '/^APP_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          chmod a+x package/build_mac_installer.sh
          package/build_mac_installer.sh $version x64

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.AppImage
            dist/*.dmg
            dist/*-macos.*.pkg

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.exe
            dist/*.AppImage
            dist/*.dmg
            dist/*-macos.*.pkg

