name: build

on: [push, pull_request]

jobs:
  build_win:
    name: Build on Windows
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          pip install https://github.com/lmdu/blobtk-wheel/releases/download/0.7.9.post1/blobtk-0.7.9.post1-cp312-none-win_amd64.whl
          pip install -r src/requirements.txt

      - name: Build executable
        run: pyinstaller package/build.spec

      - name: Package
        run: |
          $line = Select-String -Path src\config.py -Pattern 'APP_VERSION =' | Out-String
          $version = $line.Split('"')[1]
          iscc /DMyAppVersion=$version package/build_win_installer.iss
          cd dist
          7z a Circhart-v$version-win64.7z Circhart

      - uses: actions/upload-artifact@v4
        with:
          name: Circhart-win64
          path: |
            dist/*.exe
            dist/*.7z

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.exe
            dist/*.7z


  build_ubuntu:
    name: Build on Ubuntu22.04
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install build requirements
        run: |
          pip install https://github.com/lmdu/blobtk-wheel/releases/download/0.7.10.post1/blobtk-0.7.10.post1-cp312-cp312-manylinux_2_28_x86_64.whl
          pip install -r src/requirements.txt

      - name: Build executable
        run: pyinstaller package/build.spec

      - name: Package installer
        run: |
          version=`awk '/^APP_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          cd dist
          chmod a+x ../package/build_linux_desktop.sh
          ../package/build_linux_desktop.sh $version

      - uses: actions/upload-artifact@v4
        with:
          name: Dockey-ubuntu22.04
          path: |
            dist/*.deb
            dist/*.tar.gz
            dist/*.AppImage

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.deb
            dist/*.tar.gz
            dist/*.AppImage

  build_mac_arm:
    name: Build on Macos arm
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          pip install 
          pip install -r src/requirements.txt

      - name: Build executable
        run: pyinstaller package/build.spec

      - name: Package
        run: |
          version=`awk '/^APP_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          npm install --global create-dmg
          cd dist
          create-dmg Circhart.app || test -f Circhart\ 0.0.0.dmg
          mv Circhart\ 0.0.0.dmg Circhart-v${version}-macos-arm64.dmg

      - uses: actions/upload-artifact@v4
        with:
          name: Dockey-macos-arm
          path: |
            dist/*.dmg

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.dmg

  build_mac_indel:
    name: Build on MacOS intel
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          pip install
          pip install -r src/requirements.txt

      - name: Build executable
        run: pyinstaller package/build.spec

      - name: Package
        run: |
          version=`awk '/^APP_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          npm install --global create-dmg
          cd dist
          create-dmg Circhart.app || test -f Circhart\ 0.0.0.dmg
          mv Circhart\ 0.0.0.dmg Circhart-v${version}-macos-x64.dmg

      - uses: actions/upload-artifact@v4
        with:
          name: Dockey-macos-intel
          path: |
            dist/*.dmg

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.dmg
